### ISSUE TITLE
Image loading performance

### ISSUE THREAD

**Issue by jbdalton** [NYPL-Simplified/web-reader-landing-page#85]
This ticket is a placeholder for landing page performance of image/thumbs. For first-time users, many images are required to load in a short timeframe while the page waits to finish.  This creates gaps in lane viewports, where images that not visible are loading before the viewport images fill in, as the page waits to load.

Some ideas that have come up in brief discussion, in no particular order:

* Pre-sizing image box containers so that the browser doesn't have to wait to calculate for image size.
* Load 5 images instead of 10 by default for mobile (this may already be done)
* prioritizing images that are loaded to the top-of-screen lanes, and to viewport-visible images first
* making images  smaller and/or crappier
* using css sprites for lanes on landing page instead of separate image-loads
* fewer total loaded images/books upfront
* fewer lanes by default for mobile, with calls-to-action for more lanes so that those lanes and images are only visible when chosen.
* other lazy loading strategies

**Comment by EdwinGuzman** [comment]
@seanredmond As pointed out during standup, if you load the site but then quickly go without connection (while undergound), you'll get the images from the current viewport but will not get the other ones:

![image2](https://cloud.githubusercontent.com/assets/1280564/25679480/814ca314-301b-11e7-830f-b8ee2d56cf60.PNG)

![image1](https://cloud.githubusercontent.com/assets/1280564/25679456/69d1f95a-301b-11e7-9e89-67beb479012d.PNG)

I'm not a fan of this happening. Perception of loading fast is good but if you're without internet connection, you won't see anything at all. Whereas if you download all the images initially, you'll be able to view them (but can't control loading order).

I would say, since the images load very fast now let's leave out lazy loading. Arguments to use it?

CC @nodanaonlyzuul @jbdalton

**Comment by seanredmond** [comment]
Okay, good experiment. Questionable benefits. Let's skip the lazy loading and just keep the problem in mind in case any clever ideas come up.

**Comment by EdwinGuzman** [comment]
One more thing: let's say you visit the homepage and navigate around and lose internet service, when offline you'll encounter these placeholder images:

![screen shot 2017-05-03 at 5 02 54 pm](https://cloud.githubusercontent.com/assets/1280564/25681506/820a11e0-3022-11e7-91ca-50eca9a033c1.png)

These will not show up initially, however, before the actual image comes in. It's a placeholder when the browser detects that it's offline and can't get images (which are not cached). Maybe, for v2, we can load the placeholder images and then the actual book cover image.

**Comment by seanredmond** [comment]
Nice touch.

**Comment by EdwinGuzman** [comment]
@jce1028 Not adding a lazy load for v1. Adding the Milestone v2 label to this issue.

**Comment by nodanaonlyzuul** [comment]
Between optimizing the images and deciding to skip the lazy loading - is there any work really left to be done in this ticket? @seanredmond ? @EdwinGuzman ?

Can we re-open or create a new, more specific lazy-loading issue when we're more certain that we
want to take on that optimization?

Stephen

**Comment by EdwinGuzman** [comment]
I'd be okay with closing this and creating a new one later, if we need to.
